### ISSUE TITLE
Sistema de autenticação

### ISSUE THREAD

**Issue by leonardo-minora** [evatalk/eva-aa#11]
**objetivos**
- verificar qual o melhor segundo API Rest (ATOMIC, ACID, RMM)
   - rota ou método?
- token de autenticação

**Comment by mdcg** [comment]
@tenpontes, Quais perguntas a EVA poderia estar fazendo para o usuário para confirmar seus dados? (Por exemplo, E-mail, CPF, Data de nascimento)
