### ISSUE TITLE
Instruções de emissão de certificado

### ISSUE THREAD

**Issue by mdcg** [evatalk/eva-aa#14]
Para as instruções de emissão de certificado, verificar a data de realização do
curso. Para facilitar pode listar os cursos realizados, com o cod_matricula e
questionar o aluno qual curso ele deseja o certificado:

- Caso curso seja 2015 para frente, orientar o aluno a emitir o certificado no ambiente
https://ava.enap.gov.br

- Caso curso seja 2013 e 2014, orientar o aluno a emitir o certificado no ambiente
https://moodle23.enap.gov.br

- Caso seja anterior a 2013, orientar a enviar email para ead@enap.gov.br

**Comment by mdcg** [comment]
@tenpontes , como funcionará essas instruções de emissão de certificado? poderia me passar um texto exemplo ou algo do tipo só pra eu ter uma base?

**Comment by leonardo-minora** [comment]
opa @mdcg ,

pelo que lembro da conversa no ano passado:
1. para os moodles informa o caminho (hiperlinks) que o aluno precisa seguir para chegar ao PDF.
2. para o curso anterior a 2013, orientar a enviar email solicitando o envio do certificado.

@tenpontes pode confirmar se minha memória ainda é memória :P

**Comment by tenpontes** [comment]
A página http://www.enap.gov.br/pt/web/pt-br/certificados contém as instruções para emissão e validação do certificado.
